### ISSUE TITLE
[BUG] Compilation error in bms_errors_bitmask_JK_RS485_Modbus.yaml - ${bms_id} not substituted in lambda

### ISSUE THREAD

**Issue by Ferforfaen** [Sleeper85/esphome-yambms#251]
# [BUG] Compilation error in `bms_errors_bitmask_JK_RS485_Modbus.yaml` - `${bms_id}` not substituted in lambda

## Description

Compilation fails with ESPHome 2026.2.4 when using `bms_combine_JK_RS485_Modbus_bms_standard.yaml` (8x BMS). The `${bms_id}` substitution variable is not resolved inside the lambda code in `bms_errors_bitmask_JK_RS485_Modbus.yaml`, causing a C++ compile error.

[logs_yambms_run (3).txt](https://github.com/user-attachments/files/25750408/logs_yambms_run.3.txt)

[yambms (3).yaml](https://github.com/user-attachments/files/25750437/yambms.3.yaml)

## Environment

- **ESPHome version:** 2026.2.4
- **YamBMS version:** main branch (latest pull)
- **Hardware:** AtomS3R (ESP32-S3)
- **Framework:** ESP-IDF 5.5.2
- **BMS type:** JK RS485 Modbus (sniffer mode, 8x BMS)
- **Previous working version:** YamBMS v1.5.8 (with older ESPHome)

## Error

```
/data/packages/a3a4c2d8/packages/bms/bms_errors_bitmask_JK_RS485_Modbus.yaml:918:74: error: '$' was not declared in this scope
/data/packages/a3a4c2d8/packages/bms/bms_errors_bitmask_JK_RS485_Modbus.yaml:926:78: error: expected ')' before '{' token
*** [.pioenvs/yambms/src/main.cpp.o] Error 1
```

There are also warnings (not errors) about undeclared substitutions:

```
WARNING Found '${yambms_charging_rate_table}' ... 'yambms_charging_rate_table' was not declared
WARNING Found '${yambms_discharging_rate_table}' ... 'yambms_discharging_rate_table' was not declared
```

## Analysis

The error indicates that `${bms_id}` inside the lambda in `bms_errors_bitmask_JK_RS485_Modbus.yaml` is not being substituted by ESPHome before generating C++ code. The literal `$` character ends up in the compiled C++ source, causing the compiler error.

This may be related to how ESPHome 2026.x handles `vars:` substitution in nested packages with lambda expressions.

## YAML Configuration (relevant parts)

```yaml
substitutions:
  bms_update_interval: '5s'
  bms_combine_interval: '5s'
  bms_cutoff_timer: '50s'

packages:
  bms:
    url: https://github.com/Sleeper85/esphome-yambms
    ref: main
    refresh: 0s
    files:
      - path: 'packages/bms/bms_combine_JK_RS485_Modbus_sniffer.yaml'
        vars:
          sniffer_protocol: 'JK02_32S'
          sniffer_uart_id: 'uart_esp_1'
      - path: 'packages/bms/bms_combine_JK_RS485_Modbus_bms_standard.yaml'
        vars:
          bms_id: '1'
          bms_name: 'JK-BMS 1'
          bms_address: '0x01'
      # ... repeated for bms_id 2 through 8
      - path: 'packages/bms/bms_combine_JK_RS485_Modbus_bms_standard.yaml'
        vars:
          bms_id: '8'
          bms_name: 'JK-BMS 8'
          bms_address: '0x08'
```

## Full compile log

<details>
<summary>Click to expand full log</summary>

```
INFO ESPHome 2026.2.4
INFO Reading configuration /config/esphome/yambms.yaml...
INFO Updating https://github.com/Sleeper85/esphome-yambms@main
WARNING Found '${yambms_charging_rate_table}' ... 'yambms_charging_rate_table' was not declared
WARNING Found '${yambms_discharging_rate_table}' ... 'yambms_discharging_rate_table' was not declared
INFO Updating https://github.com/Sleeper85/esphome-components.git@main
INFO Detected timezone 'Europe/Copenhagen'
WARNING GPIO45 is a strapping PIN and should only be used for I/O with care.
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
INFO Generating C++ source...
INFO Compiling app... Build path: /data/build/yambms
Processing yambms (board: m5stack-atoms3; framework: espidf; platform: ...)
HARDWARE: ESP32S3 240MHz, 512KB RAM, 8MB Flash
 - framework-espidf @ 3.50502.0 (5.5.2)
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
...
/data/packages/a3a4c2d8/packages/bms/bms_errors_bitmask_JK_RS485_Modbus.yaml:918:74: error: '$' was not declared in this scope
/data/packages/a3a4c2d8/packages/bms/bms_errors_bitmask_JK_RS485_Modbus.yaml:926:78: error: expected ')' before '{' token
*** [.pioenvs/yambms/src/main.cpp.o] Error 1
========================= [FAILED] Took 22.06 seconds =========================
```

</details>

**Comment by robbedenys** [comment]
Hi, I have the exact same issue. ESPHome is at version 2026.2.4 and I get the same error trying to install YamBMS. Is there a way to fix this or should i downgrade ESPHome to an older version? Thanks for your input!

**Comment by Sleeper85** [comment]
Go to the example YAML for version `1.6.0` and add the missing substitutions `yambms_charging_rate_table` and `yambms_discharging_rate_table`.

**Comment by robbedenys** [comment]
Hi, thanks for your quick response!
After adding the missing substitutions mentioned above (yambms_charging_rate_table, yambms_discharging_rate_table, bms_cell_max_cycles), the ${bms_id} error is resolved, but there's still a GlobalsComponent error in shunt_base_minimal.yaml:

`/data/packages/a3a4c2d8/packages/shunt/shunt_base_minimal.yaml:578:113: error: no matching function for call to 'esphome::globals::GlobalsComponent<std::map<float, float> >::GlobalsComponent(int, int, int, int, int, int, int, int, int, int)'
`

It seems ESPHome 2026.x doesn't correctly parse the rate table substitutions ('100,100,100,100,100,100,100,100,100,100') when initializing the std::map<float, float> global. The 10 comma-separated values are being passed as 10 separate integer arguments instead of being parsed as a map.
Environment:

ESPHome: 2026.2.4
YamBMS: main branch
Board: LilyGo T-Connect (ESP32-S3)
BMS: JK-BMS via BLE
Shunt: Victron SmartShunt BLE

Substitutions added:
```
yamlyambms_charging_rate_table: '100,100,100,100,100,100,100,100,100,100'
yambms_discharging_rate_table: '100,100,100,100,100,100,100,100,100,100'
bms_cell_max_cycles: '6000'
```
This appears to be related to how ESPHome 2026.x handles vars: substitution in nested packages combined with globals initialization.

**Comment by Sleeper85** [comment]
It's been a while since I've been able to compile version 1.6.0 because I'm working on the development version 1.7.0. I'll do a test when I get home; that said, many people use esphome 2026.2.4 without any problems. You could also try compiling the example YAML to see if you get the same errors? Try a clean build before compiling.

**Comment by studiowena** [comment]
> It's been a while since I've been able to compile version 1.6.0 because I'm working on the development version 1.7.0. I'll do a test when I get home; that said, many people use esphome 2026.2.4 without any problems. You could also try compiling the example YAML to see if you get the same errors? Try a clean build before compiling.

sorry for OT but when 1.6.0 will be on production status? still is 1.5.8 on github

**Comment by Sleeper85** [comment]
Version 1.6.0 is the production version. Other versions remain available on GitHub.

**Comment by studiowena** [comment]
> Version 1.6.0 is the production version. Other versions remain available on GitHub.

so why latest is 1.5.8? and where is 1.6.0 then?

<img width="266" height="267" alt="Image" src="https://github.com/user-attachments/assets/82264a47-dfb2-4a00-a7ae-c51a93e7c7a2" />

**Comment by Sleeper85** [comment]
Version 1.6.0 is the one in the main branch; I'm keeping it open for bug fixes. The archive will be created before it's replaced by 1.7.0.

**Comment by studiowena** [comment]
> Version 1.6.0 is the one in the main branch; I'm keeping it open for bug fixes. The archive will be created before it's replaced by 1.7.0.

ok thanks have to replace my veriosn :) btw i've corrected wifi power + Your settings to work offline of yambms and have 60 days uptime and no F14 on deye...

**Comment by Sleeper85** [comment]
I have compiled [this 1.6.0 YAML](https://github.com/Sleeper85/esphome-yambms/blob/main/YamBMS_RP_BMS_JK-PB_RS485_Modbus.yaml) with esphome `2026.2.4` without any problems.
